### ISSUE TITLE
Unsupported MIME type: application/xml

### ISSUE THREAD

**Issue by DoubtfulTurnip** [klimeryk/dealwithit#38]
Unsure why this error occurs but once I hit the 'Deal with it' button I get this error in my browser console and the progress bar hangs.
I have tried this in MS Edge and Librewolf. I note that others have also mentioned this issue with Safari,

index.js:12  Uncaught (in promise) Error: Unsupported MIME type: application/xml
    at ee.l (index.js:12:13)
    at ee.Ht (image-bitmap.js:148:25)

I was attempting to test this with one of the example images.

I don't think it is related, but I am running this from a docker container.

Fun project, good work!

```
# Use a Node.js 18 base image
FROM node:18-alpine

# Install git for cloning the repository
RUN apk add --no-cache git

# Clone the repository into /app
RUN git clone https://github.com/klimeryk/dealwithit.git /app

# Set the working directory to /app
WORKDIR /app

# Install dependencies
RUN npm install

# Expose port (5173)
EXPOSE 5173

# Start the Vite development server with --host to allow external access
CMD ["npm", "run", "dev", "--", "--host"]
```

**Comment by tosiara** [comment]
Same error is on the prod website

**Comment by klimeryk** [comment]
Dang it, must have been caused by https://github.com/klimeryk/dealwithit/commit/d8f280b5f2e4bd612ebd87279e5954a5a90c87cb where I switched to using SVG glasses so that their color can be set to any RGBA color. I've reverted that change for now - looks like something in the production setup needs adjusting. Sorry for the breakage 🙇

**Comment by klimeryk** [comment]
And re-introduced the color changing feature in https://github.com/klimeryk/dealwithit/commit/137c6d8e7718b9471cb09d32a6b70b603d8ebe94. This time hopefully with 100% less regressions ;) But please do let me know if you notice anything off! 🙇
